### ISSUE TITLE
Error while analyzing 

### ISSUE THREAD

**Issue by security-geek** [cuckoosandbox/cuckoo#1778]
I have followed all the steps as per Cuckoo Documentation. I am using Ubuntu 16.04 version. Version of Cuckoo is 2.0-rc2. I am using vmware workstation 12 with 32-bit windows 7 professional.
 ` As shown below Cuckoo runs fine:`

> cuckoo@cuckoo-virtual-machine:~/Downloads/cuckoo$ python cuckoo.py
> 
>                      __                  
>   .----..--.--..----.|  |--..-----..-----.
>   |  __||  |  ||  __||    < |  _  ||  _  |
>   |____||_____||____||__|__||_____||_____|
> 
>  Cuckoo Sandbox 2.0-rc2
>  www.cuckoosandbox.org
>  Copyright (c) 2010-2015
> 
>  Checking for updates...
>  Good! You have the latest version available.
> 
> 2017-08-15 21:47:40,940 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/Grammar.txt
> 2017-08-15 21:47:40,969 [root] INFO: Generating grammar tables from /usr/lib/python2.7/lib2to3/PatternGrammar.txt
> 2017-08-15 21:47:41,174 [root] INFO: Updated running task ID 9 status to failed_analysis
> 2017-08-15 21:47:41,192 [lib.cuckoo.core.scheduler] INFO: Using "vmware" as machine manager
> 2017-08-15 21:47:41,618 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
> 2017-08-15 21:47:41,638 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.

When i run the analysis using the submit.py command as shown below: 

```
cuckoo@cuckoo-virtual-machine:/$ /home/cuckoo/Downloads/cuckoo/utils/submit.py --platform windows /home/cuckoo/Downloads/Samples/visioviewer32bit.exe 
Success: File "/home/cuckoo/Downloads/Samples/visioviewer32bit.exe" added as task with ID 12
```

I get the following error as shown below:

```
2017-08-15 21:47:54,107 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "visioviewer32bit.exe" (task #10, options "")
2017-08-15 21:47:54,506 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/cuckoo/Downloads/cuckoo/storage/binaries/6f9340c96e485ad1a13c092c748cc3c02d1407e989c45fe2b794776604bc6b88"
2017-08-15 21:47:54,542 [lib.cuckoo.core.scheduler] INFO: Task #10: acquired machine Windows 7 Professional - Fresh (label=/home/cuckoo/Downloads/win7/Windows 7 Professional - Fresh.vmx)
2017-08-15 21:47:54,554 [modules.auxiliary.mitm] INFO: Started mitm interception with PID 12084 (ip=192.168.37.128, port=50000).
2017-08-15 21:47:54,561 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 12085 (interface=vmnet8, host=172.16.142.128, pcap=/home/cuckoo/Downloads/cuckoo/storage/analyses/10/dump.pcap)
2017-08-15 21:47:59,735 [lib.cuckoo.core.scheduler] ERROR: Machinery error: Unable to revert snapshot for machine /home/cuckoo/Downloads/win7/Windows 7 Professional - Fresh.vmx: vmrun exited with error
2017-08-15 21:47:59,743 [lib.cuckoo.core.scheduler] CRITICAL: A critical error has occurred trying to use the machine with name Windows 7 Professional - Fresh during an analysis due to which it is no longer in a working state, please report this issue and all of the related environment details to the developers so we can improve this situation. (Note that before we would simply remove this VM from doing any more analyses, but as all the VMs will eventually be depleted that way, hopefully we'll find a better solution now).
```

Since the error was related to reverting snapshot so i tried creating snapshot using CLI as well as UI and it worked fine. 

Also, as mentioned in the other issue i have taken a snapshot of the virtual machine with agent.py running on the windows 7 machine. 

Hope someone can help me as i had been scratching my head and troubleshooting this issue for the last 8 hours but no success.

**Comment by Nwinternights** [comment]
Try Pip install -U cuckoo.

**Comment by security-geek** [comment]
It actually worked by doing the following changes:
I corrected the snapshot name as it was incorrect previously. Once i did this i got another error "cannot find .vmem file". I opened vmware workstation then delete the snapshot and recreated the snapshot and its working fine. Thanks guys for your help. Appreciate the prompt response. 


On Tuesday, 15 August 2017, 10:22:40 pm AEST, Nwinternights <notifications@github.com> wrote:


Try Pip install -U cuckoo.

**Comment by alias6466** [comment]
I believe I saw this in a previous post - update your cuckoo to latest version.

**Comment by security-geek** [comment]
getting this error now while the analysis is running. No DHCP is being used. I have assigned static IP address to host machine and virtual machine. virtual machine is connected to vmnet8 and both host and virtual machine can ping each other. 

```
2017-08-16 17:08:11,261 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.37.128.
2017-08-16 17:08:11,262 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.37.128.
2017-08-16 17:08:18,848 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.37.128.
2017-08-16 17:08:18,848 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.37.128.
2017-08-16 17:08:20,014 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.37.128.
2017-08-16 17:08:20,015 [lib.cuckoo.core.resultserver] CRITICAL: ResultServer unable to map ip to context: 192.168.37.128.
```

**Comment by jbremer** [comment]
Those ResultServer log entries simply mean that you still have a VM running while starting Cuckoo. Please upgrade to the latest version (which, among many other things, resolves this warning).

**Comment by jbremer** [comment]
Closing issue as resolved. Please reopen if you think that's not the case. Thanks!
