### ISSUE TITLE
Rooter not starting tun interface or able to reach the internet

### ISSUE THREAD

**Issue by Dhatheway** [cuckoosandbox/cuckoo#2118]
I am able to start Rooter up in debug with (cuckoo -d rooter --sudo), but when I try and start Cuckoo (cuckoo --debug) I get the error "CRITICAL: CuckooStartupError: The network interface that has been configured for VPN vpn0 is not available." When I check the dbug log of rooter I see the following

`2018-02-08 18:53:46,904 [cuckoo.apps.rooter] DEBUG: Processing command: forward_drop
2018-02-08 18:53:46,916 [cuckoo.apps.rooter] DEBUG: Processing command: state_disable
2018-02-08 18:53:46,927 [cuckoo.apps.rooter] DEBUG: Processing command: state_enable
2018-02-08 18:53:46,939 [cuckoo.apps.rooter] DEBUG: Processing command: nic_available tun0`

but Ifconfig is not showing a tun0 interface
`eth0    bla

lo       bla
virbr0   
          inet addr:192.168.100.1  Bcast:192.168.100.255  Mask:255.255.255.0'

If I manually start openvpn with my vpn0 config (sudo systemctl start openvpn@vpn0) I then get tun0 in my interfaces from ifconfig and I am able to start both cuckoo rooter and cuckoo, but the sample is not able to reach the internet, but it appears to try and use the vpn 
`2018-02-08 19:08:37,810 [cuckoo.core.scheduler] INFO: Starting analysis of URL "http://www.whatsmyip.org" (task #3373, options "procmemdump=yes,route=vpn0")`

**cuckoo rooter debug log:**
`2018-02-08 19:06:02,445 [cuckoo.apps.rooter] DEBUG: Processing command: forward_drop
2018-02-08 19:06:02,456 [cuckoo.apps.rooter] DEBUG: Processing command: state_disable
2018-02-08 19:06:02,467 [cuckoo.apps.rooter] DEBUG: Processing command: state_enable
2018-02-08 19:06:02,478 [cuckoo.apps.rooter] DEBUG: Processing command: nic_available tun0
2018-02-08 19:06:02,489 [cuckoo.apps.rooter] DEBUG: Processing command: rt_available tun0
2018-02-08 19:06:02,499 [cuckoo.apps.rooter] DEBUG: Processing command: disable_nat tun0
2018-02-08 19:06:02,509 [cuckoo.apps.rooter] DEBUG: Processing command: enable_nat tun0
2018-02-08 19:06:02,519 [cuckoo.apps.rooter] DEBUG: Processing command: flush_rttable tun0
2018-02-08 19:06:02,530 [cuckoo.apps.rooter] DEBUG: Processing command: init_rttable tun0 tun0
2018-02-08 19:06:03,308 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.101
2018-02-08 19:06:03,326 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.102
2018-02-08 19:06:03,344 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.103
2018-02-08 19:06:03,360 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.104
2018-02-08 19:06:03,380 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.105
2018-02-08 19:06:03,400 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.106
2018-02-08 19:06:03,419 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.107
2018-02-08 19:06:03,439 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.108
2018-02-08 19:06:03,458 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.109
2018-02-08 19:06:03,477 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.110
2018-02-08 19:06:03,498 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.111
2018-02-08 19:06:03,518 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.112
2018-02-08 19:06:03,538 [cuckoo.apps.rooter] DEBUG: Processing command: forward_disable virbr0 tun0 192.168.100.113`

**routing.conf**
`[vpn]
enabled = yes
vpns = vpn0

[vpn0]
name = vpn0
description = vpn0
interface = tun0
rt_table = tun0`

**/etc/iproute2/rt_tables**
255     local
254     main
253     default
0       unspec
201 tun0

**vpn0.conf**
client
dev tun0
proto udp
remote X 1194
resolv-retry infinite
remote-random
nobind
persist-key
persist-tun
route-nopull # added
auth-user-pass auth.txt
comp-lzo
verb 3
pull
fast-io
cipher AES-256-CBC
auth SHA512
<ca>
-----BEGIN CERTIFICATE-----

**Other Info**
- Ubuntu 16.04.3 LTS (fully patched)
- Cuckoo Sandbox 2.0.5
- KVM
- Physical Host
- OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
- library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08

**Comment by doomedraven** [comment]
that all looks fine, but did you patched iproute2?

**Comment by doomedraven** [comment]
never do disclosure what vpn provider do you use. in one if the issues you have my script which you need to pass to openvpn when you start it, search for route.py

**Comment by Dhatheway** [comment]
Thanks @doomedraven I'll search for it now! Also edited the post thank you.

**Comment by Dhatheway** [comment]
Still testing the script is throwing Options error: --route-up script fails with 'route.py': Permission denied in the log file which is odd as root owns all the files in /etc/openvpn but I'll keep plugging away

**Comment by doomedraven** [comment]
i heard about that permission problem, but never saw it by myself, and you not using latest openvpn, weird, i will need to dig into it once i will have a bit more of spare tiem

**Comment by Dhatheway** [comment]
Updated OpenVPN to 2.4.4 and was able to get the script to run by chmod +x the script. That said I am still not able to get a sample to talk out bound via the VPN section in Cuckoo. I still think its something with my routes as curl --interface tun0 https://api.ipify.org just hangs

**Comment by doomedraven** [comment]
post whole openvpn command how you execute it

**Comment by doomedraven** [comment]
OpenVPN 2.3.10
sudo openvpn --config Xovpn --script-security 2 --route-noexec --route-up route.py

works just fine for me, just retested

**Comment by Dhatheway** [comment]
sudo openvpn --log-append /var/log/openvpn_logs.log --config vpn0.ovpn --script-security 2 --route-noexec --route-up route.py was the command

**Comment by Dhatheway** [comment]
Looking over route.py script I don't see anything printed to the screen when I connect to the VPN calling that script. Unless I am not following right it should print out the rule and route that it adds. 

To that point I also tried running just the part that gets the vars from os.environ and it returns none for all variables. I then listed out all keys in the results from os.environ and none of those keys config, ifconfig_local, route_vpn_gateway, common_name, or dev are displayed in the results.

**Comment by doomedraven** [comment]
no idea what is wrong, it works fine here %)

**Comment by Dhatheway** [comment]
Thanks the help I'll post what I found out in case anyone else has the same problem... At this point I think its something funky I have setup as the vars are blank thus explaining why the script fails for me :)

**Comment by Dhatheway** [comment]
So I think i found part of the issue, its around the ip table.... the section in the script where it sets ip_table = common_name, my VPN is setting the common name as a strange looking thing subdomin.domain.com of the vpn provider, which dose not appear to be one of my tables after the VPN connects. When I connect the VM it looks like everything is on the "local"table.   So long short its a routing thing and I need to read up on this some more.

**Comment by doomedraven** [comment]
that is correct format, so you just not had in your iproute2 sub.domain.tld?

**Comment by Dhatheway** [comment]
yeah I had it defined as tun0 when I was reading the docs pre your script, thanks again for your help!

**Comment by doomedraven** [comment]
so all fine? :)

**Comment by vladbrinzea** [comment]
Hello all. I'm having the exact same issue as reported by Dhatheway in the initial post - either cuckoo says tun0 is down if I don't start-up openvpn myself, or if it is up everything seems to run fine but the sample is not able to reach the internet. I am running Ubuntu 16.04.04 and I've been starting openvpn the noob way - sudo service openvpn start .

doomedraven mentioned passing a script called "route.py" to openvpn when starting it up but after searching through issues for "route.py" I came up empty handed - cannot find the script nor usage instructions.

Any assistance would be highly appreciated.

**Comment by doomedraven** [comment]
`sudo openvpn --config X.ovpn --script-security 2 --route-noexec --route-up route.py`

rename it to .py only, and @vladbrinzea please stay with one issue, it hard to later figurate which is solved and which isn't, we see all of them anyway ;)
[router.py.txt](https://github.com/cuckoosandbox/cuckoo/files/1803617/router.py.txt)

**Comment by vladbrinzea** [comment]
Thank you for the quick reply @doomedraven. Will stick to this issue, other one was just a pointer :) Long-ish post ahead, highly appreciate the patience and dedication to the community that you guys display.

Still having problems getting this to work. Could you please have a look at the output and maybe let me know what I'm doing wrong? Please ignore the usage of an insecure static key, that's just to get the rest of the config up and running...

analyst@cuckoo-01:~$ sudo openvpn --config /etc/openvpn/EU_West.conf --script-security 2 --route-noexec --route-up /etc/openvpn/router.py
Mon Mar 12 17:16:45 2018 OpenVPN 2.3.10 x86_64-pc-linux-gnu [SSL (OpenSSL)] [LZO] [EPOLL] [PKCS11] [MH] [IPv6] built on Jun 22 2017
Mon Mar 12 17:16:45 2018 library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.08
Mon Mar 12 17:16:45 2018 NOTE: the current --script-security setting may allow this configuration to call user-defined scripts
Mon Mar 12 17:16:45 2018 WARNING: file '/etc/openvpn/static.key' is group or others accessible
Mon Mar 12 17:16:45 2018 WARNING: this cipher's block size is less than 128 bit (64 bit).  Consider using a --cipher with a larger block size.
Mon Mar 12 17:16:45 2018 WARNING: this cipher's block size is less than 128 bit (64 bit).  Consider using a --cipher with a larger block size.
Mon Mar 12 17:16:45 2018 TUN/TAP device tun0 opened
Mon Mar 12 17:16:45 2018 do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Mon Mar 12 17:16:45 2018 /sbin/ip link set dev tun0 up mtu 1500
Mon Mar 12 17:16:45 2018 /sbin/ip addr add dev tun0 local 10.8.0.2 peer 10.8.0.1
Mon Mar 12 17:16:45 2018 /etc/openvpn/update-resolv-conf tun0 1500 1549 10.8.0.2 10.8.0.1 init
dhcp-option DNS 172.31.0.2
ip rule add from 10.8.0.2 table None
ip route add default via 10.8.0.1 dev tun0 table None
Traceback (most recent call last):
  File "/etc/openvpn/router.py", line 16, in <module>
    subprocess.call(['ip', 'rule', 'add', 'from', local_ip, 'table', ip_table])
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
TypeError: execv() arg 2 must contain only strings
Mon Mar 12 17:16:45 2018 WARNING: Failed running command (--route-up): external program exited with error status: 1
Mon Mar 12 17:16:45 2018 UDPv4 link local (bound): [undef]

analyst@cuckoo-01:~$ sudo cat /etc/iproute2/rt_tables
[sudo] password for analyst:
#
# reserved values
#
255     local
254     main
253     default
0       unspec
#
# local
#
#1      inr.ruhep

301     ens33
311     tun0

Since we're on the topic (and I don't want to spam posts in other issues) I was hoping to clarify a few items around that script. From what I can tell, all the script does is publish a default route via "ip route add" and a rule via "ip rule". Is that correct? If yes, why is this script even needed, shouldn't Cuckoo do that automatically through the rooter? (apparently not - since vpn routing is not working on its own).

I have not found any reference to that script or its content in any of the Cuckoo or OpenVPN docs so makes me wonder - how have others gotten cuckoo vpn routing to work without it? Adding routes manually does not work since cuckoo rooter flushes the tables every analysis... Is there any other way of achieving this via openvpn config instead of having to run that script at route-up? 

All I'm trying to do is have a couple of VPNs as options as part of per-analysis-routing in Cuckoo... previous Linux and IPv4 experience, the cuckoo docs, github issues and other guides and boards have not been enough for me to get this working unfortunately, item not as well documented as other Cuckoo options...

**Comment by doomedraven** [comment]
In the another issue another person has the same error as you, so always please get and read all of related issues that will maybe help you spot peoblem before one of us jump to help you :p

Your error is there
/etc/iproute2/rt_tables

Should be different read the documentation, the router has error, but you have peinted the lines so exec them manually.

About why cuckoo doesnt do that, bcz all that values depends on the provider:custom dns

Ps never do disclosure of your vpn ip exit as that helps to build qhitelist to other side

**Comment by doomedraven** [comment]
Feel free to improve documentation id you see something missed

**Comment by doomedraven** [comment]
yup i just checked the documentation, it pretty confusing about iproute2

**Comment by doomedraven** [comment]
@vladbrinzea  check here is the improved explanation i hope https://github.com/cuckoosandbox/cuckoo/pull/2164

**Comment by vladbrinzea** [comment]
Thank you again doomedraven for taking the time. I have read the documentation extensively and reviewed all the issues I could find around using cuckoo with openvpn, have not found a solution to my problem yet. More than willing to contribute to the documentation once I find and understand the fix to this, hopefully that will help others and reduce reliance on your time.

You mentioned that the error is in rt_tables but I've just reviewed https://cuckoo.sh/docs/installation/host/routing.html and I see no difference between how I set up /etc/iproute2/rt_tables and how it's described in the documentation, could you please be more specific on where the error is if you've spotted it?

![image](https://user-images.githubusercontent.com/15797863/37334917-26691532-26a5-11e8-9d98-e689575d27f1.png)

**Comment by doomedraven** [comment]
bcz im not the cuckoo developer, im just the community guy :P 
in your open vpn you have `remote vpn.bestvpnever.com 1194`
there you have your value

**Comment by vladbrinzea** [comment]
I'm sorry but that just does not make sense to me, could you please explain the logic behind naming a routing table after the exit-point of the vpn? 
/etc/iproute2/rt_tables holds a list of separate routing tables with their IDs and names. I see no logic to changing the "name" of the routing table to the IP address or hostname of the tunnel exit point as long as the correct "name" corresponds to the interface and was specified in $CWD/conf/routing.conf, is there anything I'm missing here?

**Comment by vladbrinzea** [comment]
I'm quite comfortable using multiple routing tables and multiple gateways in linux @doomedraven that was not the issue, thank you for the link anyway. I wasn't questioning the need to define the RT in iproute2, I was just arguing you don't need to (nor should) name the table the same as your VPN gateway.

Anyway, I found the issue and solved it. The problem was that I had auto_rt = yes, under [routing] in routing.conf, which means cuckoo had control over the routing tables, _and was flushing them each time they were used._ Since I manage my own individual routing tables for the vpn connections (need to do so since I have more than one VPN connection in use, each with different purposes) that is not desirable behavior. Now that I turned auto_rt off, everything is working fine, as expected, I just need to use route-up scripts in each vpn config file to create the routes I need in their respective tables.
