### ISSUE TITLE
Guac + UWSGI + NGINX Error when attempting to connect and interact with analysis

### ISSUE THREAD

**Issue by iaji** [cuckoosandbox/cuckoo#2529]
Thanks for creating an issue! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html 
Yep!

##### My issue is:
Ill walk through my issue in steps:
1. I select a file to sandbox and upload it
    - High priority, 120 secs, inetsim
    - I enable remote control
    - I disable human interaction simulation
    - I select one of my pre configured machines
    - Time to analyze!
2.  I click on the button to interact
    - On the guac landing page I wait for things to load up, there is a loading screen and i notice a green circle by the filename
    - I then click on the remote control button.
    - after a short pause i see the error
![image](https://user-images.githubusercontent.com/27793551/46974182-4ddd8a80-d091-11e8-8cb9-ebb965112a98.png)
    - The green circle then turns red by the filename in the upper left section of the screen.  

##### My Cuckoo version and operating system are:
 - Version: 2.0.6 
I recently updated from 2.0.5
- OS: Xubuntu 16.04

###### How I installed Guac:
First I installed via package manager:
```
sudo apt install libguac-client-rdp0 libguac-client-vnc0 libguac-client-ssh0 guacd
```
I then noticed others having issues with the versioning and decided to remove those packages and install from source in the following way:
```
sudo apt -y install libcairo2-dev libjpeg-turbo8-dev libpng-dev libossp-uuid-dev libfreerdp-dev
mkdir /tmp/guac-build && cd /tmp/guac-build
wget https://www.apache.org/dist/guacamole/0.9.14/source/guacamole-server-0.9.14.tar.gz
tar xvf guacamole-server-0.9.14.tar.gz && cd guacamole-server-0.9.14
./configure --with-init-dir=/etc/init.d
make && sudo make install && cd ..
sudo ldconfig
sudo /etc/init.d/guacd start
```
Guac was up and running, no errors.

I then proceeded to configure my conf files: 
For virtualbox.conf I had to add the following line near the top of the file: 
```
 controlports = 5000-5050
```
Then for cuckcoo.conf I added the following lines at the bottom of the file:
```
[remotecontrol]
enabled = yes
guacd_host = 127.0.0.1
guacd_port = 4822
```
 SIDE NOTE: It would be nice if there was a maintained copy of the current default configuration files for each release, having to manually add in these sections after an update by combing through the issues on here isn't the most efficient.  

I then restarted the cuckoo box and allowed everything to spin back up nicely, still no errors.

I then did exactly what I laid out in the first section to get my current error.

##### The log, error, files etc can be found at:

All snippets from my cuckoo.log that are related to guac:
```
INFO: Successfully set remote control ports for virtual machine with label XXXXX@XXXXX: 5000 -5050
INFO: Successfully enabled remote control for virtual machine with label XXXXX@XXXXX on port(s): 5000-5050
```

There was nothing that stood out as out of the ordinary in the uwsgi logs

Relevant snippets in my nginx error.log:
```
2018/10/15 14:36:21 [emerg] 4068#4068: bind() to 192.168.56.1:8080 failed (99: Cannot Assign requested address) #### 192.168.56.1 is the ip for the vbox interface
2018/10/15 11:13:45 [error] 9230#9230: *120 connect() to unix:/run/uwsgi/app/cuckoo-api/socket failed (111: Connection refused) while connecting to upstream, client: X.X.X.X, server: , request: "GET /cuckoo/status HTTP/1.1", upstream: "uwsgi://unix:/run/uwsgi/app/cuckoo-api/socket:", host: "XXXXX:8090" #### There was thousands of this log line. The X.X.X.X is the ip of my cuckoo box
```
I am guessing this nginx stuff may be related to my inability to connect and interact over guac?

Guacd service brief logs:
```
User XXXXX joined connection YYYYY (1 users now present)
Loading keymap "base"
Loading keymap "en-us-kwerty"
Failed to load guacdr plugin.  Drive redirection and printing will not work.  Sound MAY not work.
Failed to load guacsnd alongside guacdr plugin.  Sound will not work.  Drive redirection and printing MAY not work.
User is not responding
User XXXX disconnected (0 users remain)
Last use of connection YYYY disconnected
Internal RDP client disconnected
Connection YYYYY removed.
```
Perhaps this user error is at fault?  I dont know where to find other guacd logs at the moment.

I can add more as needed.

**Comment by doomedraven** [comment]
side note: i can't help here, but your issues description is just amazing, didn't see one as this so much detailed like this in so much time, so just thanks

**Comment by doomedraven** [comment]
btw does it work without uwsgi?

**Comment by iaji** [comment]
@doomedraven Thanks for the compliment, I've combed through too many bad documented issues with cuckoo.  I hope it helps others follow along some.

Anyway this does indeed work when running:
```
cuckoo web runserver 0.0.0.0:8008
```
The i navigate to mycuckooip:8008 and run through the steps i typed out above.  For testing purposes this makes sense, however i do need to find a solution for a distributed deployment with nginx and uwsgi.

**Comment by doomedraven** [comment]
you are welcome, that makes much easier to help with good description :)

so for debug i would suggest to do next
put uwsgi as standalone 
you need to add this to uwsgi config

```
socket = 0.0.0.0:8008
protocol=http
```

and test if that works with remote, also check the permission on the socket
```
/run/uwsgi/app/cuckoo-api/socket
```

here kinda a good references https://monicalent.com/blog/2013/12/06/set-up-nginx-and-uwsgi/
ctrl+f for 111 and you will see 

```
chmod-socket, chown-socket, gid, uid, socket For uWSGI and nginx to communicate over a socket, you need to specify the permissions and the owner of the socket. 777 as chmod-socket is much too liberal for production. However, you may have to mess around with this number to get it correct, so everything necessary can communicate. If you don’t take care of your socket configurations, you will get errors such as:

(111: Connection refused) while connecting to upstream.
Copy
bind(): Permission denied [socket.c line 107]

```

**Comment by iaji** [comment]
So after some more poking around in logs I have come to the conclusion that the log lines I provided earlier actually are not related to this issue as I have fixed _their_ cause.  

I went through and double checked that my firewall rules were not blocking the communication of any services related to cuckoo or guacd and I believe I have everything set correctly.  

### New Findings

After combing through some more logs I found something interesting in _/var/log/uwsgi/apps_ in the **cuckoo-web.log** file:
```
[pid: 4410|app: 0|req: 11537/40003] client.IP () {44 vars in 860 bytes} [Tue Oct 16 11:26:51 2018] GET /analysis/9/control/tunnel/?read:07d07cbb-95e4-469b-8cfe-14991dfe099c:0 => generated 0 bytes in 20 msecs (HTTP/1.1 200) 9 headers in 252 bytes (0 switches on core 0)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cuckoo/web/controllers/analysis/control/api.py", line 177, in content
    guac = sockets[cache_key]
KeyError: '07d07cbb-95e4-469b-8cfe-14991dfe099c'
```

This same error has been reported in issue #2449 and has not been resolved.

Since this error occurred in my uwsgi cuckoo-web configuration I'll post some relevant config files:

### UWSGI Configurations
#### cuckcoo-web.ini
```
[uwsgi]
plugins = python
module = cuckoo.web.web.wsgi
uid = cuckoo
gid = cuckoo
static-map = /static=/usr/local/lib/python2.7/dist-packages/cuckoo/web/static
# If you're getting errors about the PYTHON_EGG_CACHE, then
# uncomment the following line and add some path that is
# writable from the defined user.
# env = PYTHON_EGG_CACHE=
env = CUCKOO_APP=web
env = CUCKOO_CWD=/home/cuckoo/.cuckoo
```
#### cuckoo-api.ini
```
[uwsgi]
plugins = python
module = cuckoo.apps.api
callable = app
uid = cuckoo
gid = cuckoo
env = CUCKOO_APP=api
env = CUCKOO_CWD=/home/cuckoo/.cuckoo
```

#### cuckoo-distributed.ini
```
[uwsgi]
plugins = python
module = cuckoo.apps.distributed
callable = app
uid = cuckoo
gid = cuckoo
env = CUCKOO_APP=dist
env = CUCKOO_CWD=/home/cuckoo/.cuckoo
```

### NGINX
#### cuckoo-web
```
upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}

server {
    listen cuckoohostIP:8000;

    # Cuckoo Web Interface
    location / {
        client_max_body_size 1G;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;
    }
}
```
#### cuckoo-api
```
upstream _uwsgi_cuckoo_api {
    server unix:/run/uwsgi/app/cuckoo-api/socket;
}

server {
    listen cuckoohostIP:8090;

    # REST API app
    location / {
        client_max_body_size 1G;
        uwsgi_pass  _uwsgi_cuckoo_api;
        include     uwsgi_params;
    }
}
```
#### cuckoo-distributed
```
upstream _uwsgi_cuckoo_distributed {
    server unix:/run/uwsgi/app/cuckoo-distributed/socket;
}

server {
    listen cuckoohostIP:9003;

    # REST Distributed app
    location / {
        client_max_body_size 1G;
        uwsgi_pass  _uwsgi_cuckoo_distributed;
        include     uwsgi_params;
    }
}
```
#### cuckoo
```
ssl_session_tickets off; # Requires nginx >= 1.5.9
    # Uncomment this next line if you are using a signed, trusted cert
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    index index.html index.htm;
    client_max_body_size 101M;
    auth_basic "Login required";
    auth_basic_user_file /etc/nginx/htpasswd;

    location / {
        proxy_pass http://127.0.0.1:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /storage/analysis {
       alias /opt/cuckoo/storage/analyses/;
       autoindex on;
       autoindex_exact_size off;
       autoindex_localtime on;
    }

    location /static {
      alias /opt/cuckoo/web/static/;
    }
}

server {
    listen cuckoohostIP:80;
    return 301 https://$server_name$request_uri;
}


server {
  listen 192.168.56.1:8080;

    root /home/cuckoo/vmshared;

     location / {
           try_files $uri $uri/ =404;
           autoindex on;
           autoindex_exact_size off;
           autoindex_localtime on;
     }
}

# Host the upstream legacy API
server {
    listen cuckoohostIP:4343 ssl http2;
    ssl_certificate /etc/nginx/ssl/cuckoo.crt;
    ssl_certificate_key /etc/nginx/ssl/cuckoo.key;
    ssl_dhparam /etc/nginx/ssl/dhparam.pem;
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
    ssl_ecdh_curve secp384r1; # Requires nginx >= 1.1.0
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off; # Requires nginx >= 1.5.9
   # Uncomment this next line if you are using a signed, trusted cert
    #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
    add_header X-Frame-Options SAMEORIGIN;
    add_header X-Content-Type-Options nosniff;
    root /usr/share/nginx/html;
    index index.html index.htm;
    client_max_body_size 101M;

    location / {
        proxy_pass http://127.0.0.1:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Restrict access
       allow cuckoohostIP;
      #allow 192.168.1.0/24;
      deny all;
    }
}
```

### Thoughts

So since the error occurs in the uwsgi **cuckoo-web.log** file I assume my issue is related to my web configuration.  I read through this: [proxying guacamole](https://guacamole.apache.org/doc/gug/proxying-guacamole.html) and havent come up with anything significant yet.  

I took a look at the implementation request page for this feature over at #2124 and there is a comment by @JamieH detailing this issue but that was back in Feb.  It details that adding the following lines to uwsgi helped:
```
processes = 1
threads = 4
```
Since it didn't specify a config to drop those lines on I'll play around with a few.

@daanfs You did a decent chunk of work implementing this, perhaps you know what a quick fix would be?

**Comment by iaji** [comment]
Well adding:
```
processes = 1
threads = 4
```
To my **cuckoo-web.ini** uwsgi config seemed to have fixed the main connection issue.  

I can now interact with the VM through the web-gui but it still glitches and errors out intermittently.  

In the uwsgi logs in **cuckoo-web.log** file I have found this new error:
```
Tue Oct 16 14:58:48 2018 - uwsgi_response_write_body_do(): Broken pipe [core/writer.c line 419] during GET /analysis/10/control/tunnel/?read:dd561025-1428-4897-afa0-ab6db8890aa0:50 (129.73.145.160)
IOError: write error
```

I'll look into this more...

**Comment by iaji** [comment]
My setup is stable enough for now, this can be closed.  I'm interested in helping improve the documentation on Cuckoo, specifically for little things like the fix above.

**Comment by Geldy1** [comment]
I'm getting this same issue, although the change to cuckoo-web.ini uwsgi config didn't fix the issue for me. I'm able to get a remote session no problem when bypassing nginx/uwsgi, but I'm getting the static screen otherwise. I do see the following error in mycuckoo-web.ini log. 

> No handlers could be found for logger "cuckoo.web.controllers.analysis.control.api"

**Comment by brockrob** [comment]
Adding 

`uwsgi_buffering off;`

to my nginx config seems to have helped a lot.

**Comment by xcampax** [comment]
I had the same issue and this solved it for me:

> ```
> processes = 1
> threads = 4
> ```

Thanks!

**Comment by bdevel** [comment]
I got Guac remote control working using these configs:

`/etc/nginx/sites-available/cuckoo-web.conf`

```
upstream _uwsgi_cuckoo_web {
    server unix:/run/uwsgi/app/cuckoo-web/socket;
}

server {
    uwsgi_buffering off; # disable for guac
    listen 80;

    # Cuckoo Web Interface
    location / {
        client_max_body_size 1G;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Proto $scheme;
        uwsgi_pass  _uwsgi_cuckoo_web;
        include     uwsgi_params;
        # Make Guac work https://guacamole.apache.org/doc/gug/proxying-guacamole.html
        proxy_buffering off;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $http_connection;
    }
}

```

I think the `proxy_buffering off;` and `uwsgi_buffering off;` are the most important.

**Comment by cvandeplas** [comment]
For me the following solved the issue:
1/ adding to `cuckoo-web.ini` (uwsgi configuration)
```
processes = 1
threads = 4
```
2/ adding in the `server` section of `cuckoo-web.conf`  (nginx configuration). 
```
    uwsgi_buffering off; # disable for guac
```
The second point is needed as otherwise the screen works a few seconds, and is then lost.

3/ also for editing the `/usr/local/lib/python2.7/dist-packages/cuckoo/web/analysis/urls.py` to `exempt_csrf` for_only_ the  `control/tunnel` page.  (the `tasks/info` one is not needed)
![image](https://user-images.githubusercontent.com/12810839/60563775-c1463a00-9d8f-11e9-868d-0830eee69546.png)
This patch was mentioned here: https://github.com/cuckoosandbox/cuckoo/issues/2771#issuecomment-507935698
