### ISSUE TITLE
Analysis aborts after critical timeout and log folder does not exist

### ISSUE THREAD

**Issue by PatriciaInfante** [cuckoosandbox/cuckoo#730]
Hello, I would like to ask for some help regarding this error. I have been working on this in weeks by setting up and configuring the network setting connections. Hoping for your help. After submitting the malware via submit.py, and waiting the critical timeout to finish, the analysis aborts and the log folder of the analyses is not produced. I attached here the log in the log folder and the zip contains the report and dump.pcap file.
[cuckoo.txt](https://github.com/cuckoosandbox/cuckoo/files/97176/cuckoo.txt)

[report and dump.zip](https://github.com/cuckoosandbox/cuckoo/files/97183/report.and.dump.zip)

2016-01-20 16:15:32,164 [lib.cuckoo.core.scheduler] INFO: Using "virtualbox" machine manager
2016-01-20 16:15:34,458 [lib.cuckoo.core.scheduler] INFO: Loaded 1 machine/s
2016-01-20 16:15:34,464 [lib.cuckoo.core.scheduler] INFO: Waiting for analysis tasks.
2016-01-20 16:15:53,068 [lib.cuckoo.core.scheduler] INFO: Starting analysis of FILE "/home/patricia/Desktop/MalwareSamples/Win32.Polip.a/Win32.Polip.a.exe" (task=4)
2016-01-20 16:15:53,096 [lib.cuckoo.core.scheduler] INFO: File already exists at "/home/patricia/Desktop/cuckoo2/storage/binaries/f4855d1b10f7ab1a2e6b99016437f72c5f98579d69f08b6312cc24400f483177"
2016-01-20 16:15:53,244 [lib.cuckoo.core.scheduler] INFO: Task #4: acquired machine CSGWin (label=CSGWin)
2016-01-20 16:15:53,250 [modules.auxiliary.sniffer] INFO: Started sniffer with PID 6091 (interface=vboxnet0, host=192.168.56.101, dump path=/home/patricia/Desktop/cuckoo2/storage/analyses/4/dump.pcap)
2016-01-20 16:15:56,197 [lib.cuckoo.core.guest] INFO: Starting analysis on guest (id=CSGWin, ip=192.168.56.101)
2016-01-20 16:25:56,209 [lib.cuckoo.core.scheduler] ERROR: CSGWin: the guest initialization hit the critical timeout, analysis aborted.
2016-01-20 16:25:58,504 [modules.processing.behavior] WARNING: Analysis results folder does not exist at path "/home/patricia/Desktop/cuckoo2/storage/analyses/4/logs".
2016-01-20 16:26:07,086 [lib.cuckoo.core.scheduler] INFO: Task #4: reports generation completed (path=/home/patricia/Desktop/cuckoo2/storage/analyses/4)
2016-01-20 16:26:07,245 [lib.cuckoo.core.scheduler] INFO: Task #4: analysis procedure completed

**Comment by jbremer** [comment]
There's definitely something going wrong with your network setup. Does your VM have the correct IP address (`192.168.56.101`) as per documentation / configuration?

**Comment by PatriciaInfante** [comment]
Yes, the VM has 192.168.56.101 and subnet mask 255.255.255.0. My host (Linux Mint) has inet addr:192.168.56.1  Bcast: 192.168.56.255  Mask: 255.255.255.0 under vboxnet0.

**Comment by jbremer** [comment]
Does the VM have a gateway?

**Comment by PatriciaInfante** [comment]
I left the gateway blank. I assigned 192.168.56.1 as the preferred DNS server. In the network settings, I assigned two network adapters, NAT (Adapter type: PCNet Fast III) and Host-only  (Adapter type: Intel Pro/1000 MT Server 82545 EM). 

In the preferences, the host-only network details of vboxnet0 are 
ipv4 address: 192.168.56.1
ipv4 network address: 255.255.255.0
The enable server checkbox under DHCP Server tab is unchecked.

**Comment by jbremer** [comment]
Well, you should probably not leave the gateway blank ;)

**Comment by PatriciaInfante** [comment]
Owww. What should it have then?  :pray:

**Comment by jbremer** [comment]
192.168.56.1

**Comment by jbremer** [comment]
192.168.56.1

**Comment by PatriciaInfante** [comment]
Hello Sir, I tested it again. The results are still the same. I attached here the report and dump of the latest task. I ran it via python cuckoo.py --debug. Kindly take a look at the log file
[Report,log,dump.zip](https://github.com/cuckoosandbox/cuckoo/files/97543/Report.log.dump.zip)

**Comment by PatriciaInfante** [comment]
Hi, I fixed it already. This time, I first made sure that they are able to ping at each other. Changed the ip address of the Windows XP from 192.168.56.101 to 192.168.56.10. Also, since the ipv4 address in the host-only network details under the Preferences  is 192.168.56.1, I also assigned it as the gateway in the Windows XP. I emptied out the DNS server part below the manual configuration. Lastly, I took a snapshot of it and changed the ip address in the virtualbox configuration file. It is all working and looking good now. Thank you @jbremer for the time!

**Comment by shirinmgh** [comment]
Hi, From the last comment I understand this steps for solving the problem:
1) Set the ip address of windows xp to 192.168.56.10
2) Set the gateway of windows XP to ip address of host
3) Set blank of DNS server part
4) Take a snapshot of vm (win XP)
5) But I can't understand the last statement "changed the ip address in the virtualbox configuration file" 
please explain about it

**Comment by PatriciaInfante** [comment]
Oww, hi! well, there is a virtualbox.conf, I edited this because I was using Oracle virtualbox (use other conf file if you are using vmware). In virtualbox.conf, you have to specify the ip so that the Cuckoo knows what is the ip of your virtualbox to use. :)

**Comment by shirinmgh** [comment]
I trie'd a lot, and fixed all of them but my cuckoo has this error so, can you help me? what is wrong?

**Comment by hwsamuel** [comment]
I have the exact same issue and followed the specified steps, but my issue is not resolved. Is there any way to determine what could be causing this?

**Comment by breuerp** [comment]
If you've verified that the IP settings on your XP guest are correct and they match what's in virtualbox.conf, try taking a snapshot of your XP VM while it's running.  That has occasionally solved this issue.

**Comment by Jynis2937** [comment]
I think my network configuration between host and vm in virtualbox.conf, cuckoo.conf are valid, but still suffer from this issue. Host can get ping packets from vm. (however vm can get nothing from host) Is this issue occured due to firewall policy?

**Comment by doomedraven** [comment]
Could be, try curl vm_ip:8000 if you eill get error 50x it means communication works, but yah you should shitdown the windows firewall or allow agent communication

**Comment by Jynis2937** [comment]
I've found some reasons and finally resolved them.
1. Created host-only interface for virtualbox 
`vboxmanage hostonlyif create`
`vboxmanage hostonlyif ipconfig vboxnet0 --ip 192.168.56.1`

`vboxmanage modifyvm {vm-name} --hostonlyadapter1 vboxnet0`
`vboxmanage modifyvm {vm-name} --nic1 hostonly`
^-- it having no effect, manually set at VirtualBox Network setting tab. I did.

2. Windows XP firewall was automatically on. I unchecked it. 
3. Add IPtables rules to use guest pc network like NAT.
`iptables -A FORWARD --out-interface eth0 --in-interface vboxnet0 --source 192.168.56.0/24 --match conntrack --ctstate NEW -j ACCEPT`
`iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT`
`iptables -A POSTROUTING -t nat -j MASQUERADE`

4. Set 'MASQUERADE' to forward guest pc does.
`sysctl -w net.ipv4.ip_forward=1`
`sysctl -p`

**Comment by Jynis2937** [comment]
Refered to this blog, http://lab.diano.kr/52. The ABSOLUTE one I've ever read.

**Comment by doomedraven** [comment]
why just not read the official documentation? :P

**Comment by Jynis2937** [comment]
Ok ill watch them later. frankly speaking, it takes longer than works with my language ^오^
